TaskScheduler/urls.py
"""
Definition of urls for TaskScheduler.
"""

from datetime import datetime
from django.conf.urls import url, include
from django.contrib import admin
import django.contrib.auth.views

import app.forms
import app.views

# Uncomment the next lines to enable the admin:
# from django.conf.urls import include
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = [

	url(r'^admin', include(admin.site.urls)),
	url(r'^scheduler/', include("task_scheduler.urls")),
    
]

task_scheduler/urls.py
from django.conf.urls import url
from . import views
from .views.login_and_registration import views as loginviews
from .views.budget import views as budgetviews
from .views.user_profile import views as userviews

urlpatterns = [
	
	url(r'^index$', budgetviews.index, name='index'),

	url(r'^budget$', budgetviews.get_budget, name='budget_no_params'),
	url(r'^budget/(?P<set_mode>\w+)/(?P<start_week_date>\d+)$', budgetviews.get_budget, name='budget'),
	url(r'^editbudget/(?P<budget_pk>\d+)/(?P<page_number>\d+)$', budgetviews.edit_budget, name='editbudget'),
	url(r'^deletebudget/(?P<budget_pk>\d+)/(?P<page_number>\d+)$', budgetviews.delete_budget, name='deletebudget'),
	url(r'^newspending$', budgetviews.add_budget, name='newspending'),

	url(r'^register$', loginviews.register, name='register'),
	url(r'^login$', loginviews.login, name='login'),
	url(r'^logout$', loginviews.logout, name='logout'),

	url(r'^profile$', userviews.profile, name='profile'), 
	
]

task_scheduler/models.py
from django.db import models

# Create your models here.

class User(models.Model):
	username = models.CharField(max_length=20, unique=True)
	first_name = models.CharField(max_length=50)
	last_name = models.CharField(max_length=50)
	email = models.EmailField(unique = True)
	password = models.CharField(max_length=200)
	monthly_budget_target = models.DecimalField(decimal_places=2, max_digits=99)
	total_saving = models.DecimalField(decimal_places=2, max_digits=99)

	def __str__(self):
		return self.first_name

class DebitOrCredit(models.Model):
	type = models.CharField(max_length=10)

	def __str__(self):
		return self.type

class Task(models.Model):
	task_name = models.CharField(max_length=50)
	start_date = models.DateField()
	end_date = models.DateField()
	description = models.TextField()
	user = models.ForeignKey("User", on_delete=models.CASCADE)

	def __str__(self):
		return self.task_name

class Currency(models.Model):
	currency_name = models.CharField(max_length=50)
	class Meta:
		verbose_name_plural = "Currencies"

	def __str__(self):
		return self.currency_name

class BudgetTypeManager(models.Manager):
    def create_budget_type(self, type_name, debit_or_credit, user):
        budget_type = self.create(type_name = type_name, debit_or_credit = debit_or_credit, user = user)
        
        return budget_type

class BudgetType(models.Model):
	type_name = models.CharField(max_length=50)
	debit_or_credit = models.ForeignKey("DebitOrCredit", on_delete=models.CASCADE)
	user = models.ForeignKey("User", on_delete=models.CASCADE)
	objects = BudgetTypeManager()

	def __str__(self):
		return self.type_name


class Budget(models.Model):
	name = models.CharField(max_length=50)
	date = models.DateField()
	amount = models.DecimalField(decimal_places=2, max_digits=99)
	user = models.ForeignKey("User", on_delete=models.CASCADE)
	type = models.ForeignKey("BudgetType", on_delete=models.CASCADE,)
	#currency = models.ForeignKey("Currency", on_delete=models.CASCADE)

	def __str__(self):
		return self.name
	

task_scheduler/forms.py
from django import forms
from .models import Budget, User
import bcrypt

class BudgetForm(forms.ModelForm):
	class Meta:
		model = Budget
		fields = ('name', 'date', 'amount',)
		
class UserForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'password', 'monthly_budget_target', 'total_saving',)
		widgets = {
			'password': forms.PasswordInput(),
		}
	def save(self, commit=True):
		user = super(UserForm, self).save(commit=False)
		encrypted_password = bcrypt.hashpw(self.cleaned_data.get("password").encode('utf-8'), bcrypt.gensalt())
		user.password = encrypted_password
		if commit:
			user.save()
		return user

task_scheduler/login_and_registration/views.py
from django.shortcuts import render, render_to_response, redirect
from task_scheduler.models import User
from task_scheduler.forms import UserForm
import bcrypt
import datetime

def register(request):
	if (request.method == "POST"):
		form = UserForm(request.POST)
		if (form.is_valid):
			user = form.save(commit=False)
			user.save()
		return redirect("/scheduler/index")
	else:
		form = UserForm
		return render(request, template_name="task_scheduler/register.html", context={'form': form})

def login(request):
	if (request.method == "POST"):
		username = request.POST.get("username")
		password = request.POST.get("password")
		
		user = User.objects.get(username = username)
		if (bcrypt.hashpw(password.encode('utf-8'), user.password.encode('utf-8')) == user.password.encode('utf-8')):
			request.session['User'] = user.id
			request.session['Username'] = user.username
			return redirect('/scheduler/index')
		else:
			return render(request, template_name="task_scheduler/login.html")
	else:
		return render(request, template_name="task_scheduler/login.html")

task_scheduler/views/budget/views.py
from django.shortcuts import render, render_to_response, redirect
from task_scheduler.models import Budget, User, BudgetType, DebitOrCredit
from task_scheduler.forms import BudgetForm
import bcrypt
import datetime
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from _datetime import timedelta, date
import locale

def index(request):
	return render(request, template_name="task_scheduler/index.html")

def count_income(budgets):
	income = 0
	for budget_item in budgets:
		
		if (budget_item.type.debit_or_credit.type == 'Credit'):
			income += budget_item.amount
			
		#else:
		#	total += budget_item.amount

	return income

def count_total(budgets):
	total = 0
	
	for budget_item in budgets:
		
		if (budget_item.type.debit_or_credit.type == 'Debit'):
			total += budget_item.amount
			
		#else:
		#	total += budget_item.amount

	return total

def get_budget(request, set_mode="", start_week_date = ""):

	exact_date = ""
	week_start_date = ""
	week_end_date = ""
	exact_month = ""
	exact_year = ""

	if request.method == "GET": 
		
		if 'User' in request.session:
			user = User.objects.get(pk = request.session['User'])
			num = []
			
			for y in range(2016, datetime.datetime.now().year+5):
				num.append(y)

			if set_mode == "":
				mode = "recent"
				start_date = datetime.datetime.strptime(str(date.today()),"%Y-%m-%d") + timedelta(days = -7)
				budgets_all = Budget.objects.filter(user_id = user.id)
			elif set_mode == "week":
				mode = "weekpicker"
				start_date = start_week_date[0:2]
				month = start_week_date[2:4]
				year = start_week_date[4:8]
				
				thirty_one_month = ["01", "03", "05", "07", "08", "10", "12"]

				
				start_week = datetime.datetime.strptime(str(year) + '-' + str(month) + '-' + str(start_date), "%Y-%m-%d")

				if start_date == "22":
					end_week = start_week + timedelta(days = 5)
				elif start_date != "28":
					end_week = start_week + timedelta(days = 6)
				elif month == "02" and int(year)%4 != 0:
					end_week = start_week
				elif month == "02" and int(year)%4 == 0:
					end_week = start_week + timedelta(days = 1)
				elif month in thirty_one_month:
					end_week = start_week + timedelta(days = 3)
					
				else:
					end_week = start_week + timedelta(days = 2)
							
				budgets_all = Budget.objects.filter(user_id = user.id).filter(date__range = [start_week, end_week]).order_by('date', 'id')
				week_start_date = start_week
				week_end_date = end_week

			elif set_mode == "month":
				mode = "monthpicker"
				month_year = start_week_date
				month = start_week_date[0:2]
				year = start_week_date[2:6]
				start_weeks = []
				start_dates = ["01", "08", "15", "22", "28"]
				thirty_one_month = ["01", "03", "05", "07", "08", "10", "12"]
				week_spendings = []
				week_incomes = []
				exact_month = month + "/" + year
				for start_date in start_dates:
					start_week = datetime.datetime.strptime(str(year) + '-' + str(month) + '-' + str(start_date), "%Y-%m-%d")

					if start_date == "22":
						end_week = start_week + timedelta(days = 5)
					elif start_date != "28":
						end_week = start_week + timedelta(days = 6)
					elif month == "02" and int(year)%4 != 0:
						end_week = start_week
					elif month == "02" and int(year)%4 == 0:
						end_week = start_week + timedelta(days = 1)
					elif month in thirty_one_month:
						end_week = start_week + timedelta(days = 3)
						
					else:
						end_week = start_week + timedelta(days = 2)
						

					budgets = Budget.objects.filter(user_id = user.id).filter(date__range = [start_week, end_week]).order_by('date', 'id')
					week_spending = count_total(budgets)
					week_income = count_income(budgets)

					start_weeks.append(str(start_date) + str(month) + str(year))
					
					week_spendings.append(week_spending)
					week_incomes.append(week_income)

				
				total_spending = 0
				total_income = 0

				for spending in week_spendings:
					total_spending += spending
				for income in week_incomes:
					total_income += income

				monthly_balance = total_income - total_spending
				monthly_budget_target = user.monthly_budget_target
				return render(request, template_name="task_scheduler/budget.html", context={'budgets': budgets,
																						'num': num,
																						'total': total_spending,
																						'income': total_income,
																						'week_spendings': week_spendings,
																					    'week_incomes': week_incomes,
																					    'mode': mode,
																					    'start_weeks': start_weeks,
																					    'monthly_balance': monthly_balance,
																					    'monthly_budget_target': monthly_budget_target,
																					    'exact_month': exact_month, })
			
			paginator = Paginator(budgets_all, 6)

			page = request.GET.get('page')
			
			try:
				budgets = paginator.page(page)
			except PageNotAnInteger:
				# If page is not an integer, deliver first page.
				budgets = paginator.page(1)
			except EmptyPage:
				# If page is out of range (e.g. 9999), deliver last page of results.
				budgets = paginator.page(paginator.num_pages)

			
			total_spending = count_total(budgets_all)
			income = count_income(budgets_all)
			number_of_pages = range(0, paginator.num_pages)
			return render(request, template_name="task_scheduler/budget.html", context={'budgets': budgets,
																						'num': num,
																						'total': total_spending,
																					    'income': income,
																					    'mode': mode,
																					    'number_of_pages': number_of_pages,
																					    'week_start_date': week_start_date,
																					    'week_end_date': week_end_date, })
		else:
			return redirect('/scheduler/login')

	elif request.method == "POST":
		if 'User' in request.session:
			user = User.objects.get(pk = request.session['User'])
			num = []
			for y in range(2016, datetime.datetime.now().year+1):
				num.append(y)
			
			mode = request.POST.get("selectpicker")
			
			if mode == "all":
				budgets = Budget.objects.filter(user_id = user.id).order_by('date', 'id')
				
			elif mode == "datepicker":
				search_date = request.POST.get("datepicker")
				budgets = Budget.objects.filter(user_id = user.id).filter(date = search_date).order_by('date', 'id')
				exact_date = datetime.datetime.strptime(search_date,"%Y-%m-%d")
			elif mode == "weekpicker":
				start_date = request.POST.get("datepicker")
				end_date = datetime.datetime.strptime(start_date,"%Y-%m-%d") + timedelta(days = 6)
				budgets = Budget.objects.filter(user_id = user.id).filter(date__range = [start_date, end_date]).order_by('date', 'id')
				week_start_date = datetime.datetime.strptime(start_date,"%Y-%m-%d")
				week_end_date = end_date
			elif mode == "monthpicker":
				month_year = request.POST.get("datepicker")
				month = month_year[0:2]
				year = month_year[3:7]
				start_weeks = []
				start_dates = ["01", "08", "15", "22", "28"]
				week_spendings = []
				week_incomes = []
				thirty_one_month = ["01", "03", "05", "07", "08", "10", "12"]
				exact_month = month + "/" + year
				for start_date in start_dates:
					start_week = datetime.datetime.strptime(str(year) + '-' + str(month) + '-' + str(start_date), "%Y-%m-%d")
					
					if start_date == "22":
						end_week = start_week + timedelta(days = 5)
					elif start_date != "28":
						end_week = start_week + timedelta(days = 6)
					elif month == "02" and int(year)%4 != 0:
						end_week = start_week
					elif month == "02" and int(year)%4 == 0:
						end_week = start_week + timedelta(days = 1)
					elif month in thirty_one_month:
						end_week = start_week + timedelta(days = 3)
						
					else:
						end_week = start_week + timedelta(days = 2)
						
					budgets = Budget.objects.filter(user_id = user.id).filter(date__range = [start_week, end_week]).order_by('date', 'id')
					week_spending = count_total(budgets)
					week_income = count_income(budgets)
					
					start_weeks.append(str(start_date) + str(month) + str(year))
					
					week_spendings.append(week_spending)
					week_incomes.append(week_income)

				
				total_spending = 0
				total_income = 0

				for spending in week_spendings:
					total_spending += spending
				for income in week_incomes:
					total_income += income

				monthly_balance = total_income - total_spending
				monthly_budget_target = user.monthly_budget_target
				return render(request, template_name="task_scheduler/budget.html", context={'budgets': budgets,
																						'num': num,
																						'total': total_spending,
																						'income': total_income,
																						'week_spendings': week_spendings,
																					    'week_incomes': week_incomes,
																					    'mode': mode,
																					    'start_weeks': start_weeks,
																					    'monthly_balance': monthly_balance,
																					    'monthly_budget_target': monthly_budget_target,
																					    'exact_month': exact_month, })
			elif mode == "yearpicker":
				month_spendings = []
				month_incomes = []
				year = request.POST.get("yearpicker")
				for i in range(1, 13):
					budgets = Budget.objects.filter(user_id = user.id).filter(date__year = request.POST.get("yearpicker")).filter(date__month = i).order_by('date', 'id')
					month_spending = count_total(budgets)
					month_income = count_income(budgets)

					month_spendings.append(month_spending)
					month_incomes.append(month_income)

				total_spending = 0
				total_income = 0

				for spending in month_spendings:
					total_spending += spending
				for income in month_incomes:
					total_income += income

				paginator = Paginator(budgets, 6)
				page = request.GET.get('page')

				try:
					budgets = paginator.page(page)
				except PageNotAnInteger:
				# If page is not an integer, deliver first page.
					budgets = paginator.page(1)
				except EmptyPage:
				# If page is out of range (e.g. 9999), deliver last page of results.

task_scheduler/views/login_and_registration/views.py
from django.shortcuts import render, render_to_response, redirect
from task_scheduler.models import User
from task_scheduler.forms import UserForm
import bcrypt
import datetime

def register(request):
	if (request.method == "POST"):
		form = UserForm(request.POST)
		if (form.is_valid):
			user = form.save(commit=False)
			user.save()
		return redirect("/scheduler/index")
	else:
		form = UserForm
		return render(request, template_name="task_scheduler/register.html", context={'form': form})

def login(request):
	if (request.method == "POST"):
		username = request.POST.get("username")
		password = request.POST.get("password")
		
		user = User.objects.get(username = username)
		if (bcrypt.hashpw(password.encode('utf-8'), user.password.encode('utf-8')) == user.password.encode('utf-8')):
			request.session['User'] = user.id
			request.session['Username'] = user.username
			return redirect('/scheduler/index')
		else:
			return render(request, template_name="task_scheduler/login.html")
	else:
		return render(request, template_name="task_scheduler/login.html")

def logout(request):
	del request.session['User']
	return redirect('/scheduler/login')

task_scheduler/views/user_profile/views.py
from django.shortcuts import render, render_to_response, redirect
from task_scheduler.models import Budget, User, BudgetType, DebitOrCredit
from task_scheduler.forms import BudgetForm
import bcrypt
import datetime
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from _datetime import timedelta, date
import locale

def profile(request):
	if request.method == 'GET':
		if 'User' in request.session:
			user = User.objects.get(pk = request.session['User'])
			return render(request, template_name="task_scheduler/profilepage.html", context={'user' : user,
																					  })
		else:
			return redirect("/scheduler/budget/login")
	else:
		if 'User' in request.session:
			maketrans = str.maketrans
			user = User.objects.get(pk = request.session['User'])
			user.first_name = request.POST.get('id_first_name')
			user.last_name = request.POST.get('id_last_name')
			
			monthly_budget = request.POST.get('id_monthly_budget')
			monthly_budget = monthly_budget.translate(maketrans(',.', '.,'))
			monthly_budget = monthly_budget.replace(",", "")
			monthly_budget = monthly_budget.replace("Rp", "")

			user.monthly_budget_target = monthly_budget

			user.save()
			return redirect("/scheduler/budget/profile")
		else:
			return redirect("/scheduler/budget/login")

task_scheduler/templates/task_scheduler/editbudget.html
{% extends 'task_scheduler/layout/top-nav.html' %}
{% load staticfiles %}
{% load humanize %}
{% block footer %}
	<script>
	$("#id_date").datepicker({
		showOn: "focus",
		dateFormat: "yy-mm-dd"
	
	});
	$('#id_amount').inputmask({ 'mask': "9{0,5}[.9{0,2}]", greedy: false });
	</script>
{% endblock %}
{% load widget_tweaks %}

{% block content_title %}
Edit Budget
{% endblock %}

{% block content %}

	<div class="box" style="width:70%; margin:auto; padding:25px">
		
			<div class="box-body">
				<form method="POST" class="post-form">{% csrf_token %}
					<div class="input-group">
						<span class="input-group-addon"><i class="fa fa-cart-arrow-down"></i></span>
						<input id="id_name" name="id_name" class="form-control" type="text" value="{{ budget.name }}" />
					</div>
					<div class="input-group">
						<span class="input-group-addon"><i class="fa fa-calendar-check-o"></i></span>
						<input id="id_date" name="id_date" class="form-control" type="text" value="{{ budget_date }}" />
					</div>
					<div class="input-group">
						<span class="input-group-addon"><i class="fa fa-money"></i></span>
						<input id="id_amount" name="id_amount" class="form-control" type="text" value="{{ budget.amount|intcomma }}" />
					</div>
					<div class="input-group">
						
						<span class="input-group-addon"><i class="fa fa-shopping-basket"></i></span>
						<select id="id_type" name="id_type" class="form-control">
							{% for type in budget_type %}
								{% if type == budget.type %}
									<option selected="selected" value="{{ type.id }}">{{ type }}</option>
								{% else %}
									<option value="{{ type.id }}">{{ type }}</option>
								{% endif %}
							{% endfor %}
						</select>
					</div>
					<br />
				
				<button type="submit" class="save btn btn-primary">Save</button>
				</form>
			</div>
	</div>

{% endblock %}

task_scheduler/templates/task_scheduler/index.html
{% extends "task_scheduler/layout/top-nav.html" %}
{% load staticfiles %}
{% block title %}
	Home
{% endblock %}

{% block header %}

{% endblock %}

{% block content_title %}
	Home
{% endblock %}

{% block content_header %}
	Home
{% endblock %}

{% block content %}
	Home
{% endblock %}

task_scheduler/templates/task_scheduler/login.html
{% extends 'task_scheduler/layout/top-nav.html' %}
{% load staticfiles %}

{% block content_title %}
Login
{% endblock %}

{% block content %}

	<div class="box" style="width:70%; margin:auto; padding:25px">
		<form method="POST" action="/scheduler/login" class="post-form">{% csrf_token %}
		<div class="box-body">
			<div class="input-group">
				<span class="input-group-addon"><i class="fa fa-user"></i></span>
				<input id="username" name="username" class="form-control" type="text" required="required" placeholder="username" />
			</div>
			<br />
			<div class="input-group">
				<span class="input-group-addon"><i class="fa fa-key"></i></span>
				<input id="password" name="password" class="form-control" type="password" required="required" placeholder="password" />
			</div>
			<br />
			<button type="submit" class="save btn btn-primary">Save</button>
		</div>
    </form>
	</div>

{% endblock %}

task_scheduler/templates/task_scheduler/newspending.html
{% extends 'task_scheduler/layout/top-nav.html' %}
{% load staticfiles %}

{% block header %}

{% endblock %}
{% block footer %}
	<script type="text/javascript">
	$("#id_date").datepicker({
		showOn: "focus",
		dateFormat: "yy-mm-dd"
		
	});

	// Wait for the page to load first

		//Get a reference to the link on the page
		// with an id of "mylink"
		var a = $("#addbudget");

		//Set code to run when the link is clicked
		// by assigning a function to "onclick"
		a.click(function () {
			$("#div_type_name").css("display", "table")
			$("#div_type_creditordebit").css("display", "table")
			return false;

		});

		$("#add-budget").submit(function () {
			
			var type = ($("#id_type").val());
			
			if ($("#id_type").val() == "none") {

				if ($("#type_name").val() == "" && ($("#type_creditordebit").val() == "none")) {
					alert("Please fill budget type, or add new budget type")

					return false;
				}
			}

			else {
				
				if ($("#type_name").val() != "" || ($("#type_creditordebit").val() != "none")) {
					alert("You cannot fill budget type and add new budget type at the same time")
					debugger;
					return false;
				}
			}
		})
	</script>
{% endblock %}
{% load widget_tweaks %}

{% block content_title %}
New Spending
{% endblock %}

{% block content %}

	<div class="box" style="width:70%; margin:auto; padding:25px">
		
			<div class="box-body">
				<form method="POST" id="add-budget" class="post-form">{% csrf_token %}
					{{ form.non_field_errors }}
					<div class="input-group">
						{{ form.name.errors }}
						<span class="input-group-addon"><i class="fa fa-cart-arrow-down"></i></span>
						{% render_field form.name class="form-control" placeholder="Transaction" %}
					</div>
					<div class="input-group">
						{{ form.date.errors }}
						<span class="input-group-addon"><i class="fa fa-calendar-check-o"></i></span>
						{% render_field form.date class="form-control" placeholder="Date" %}
					</div>
					<div class="input-group">
						{{ form.amount.errors }}
						<span class="input-group-addon"><i class="fa fa-money"></i></span>
						{% render_field form.amount class="form-control" placeholder="Amount" %}
					</div>
					<div class="input-group">
						<span class="input-group-addon"><i class="fa fa-shopping-basket"></i></span>
						<select id="id_type" name="type" class="form-control">
							<option value="none">--- Select Transaction Types ---</option>
							{% for type in types %}
								<option value="{{ type.id }}">{{ type }}</option>
							{% endfor %}
						</select>
					</div>
					<div class="input-group" style="padding-top:15px; padding-bottom:15px">
						<a id="addbudget" href="#" class="btn btn-warning"><span class="fa fa-plus"></span>  Add Budget Type</a>
					</div>
					<div class="input-group" id="div_type_name" style="display:none">
						<span class="input-group-addon"><i class="fa fa-shopping-basket"></i></span>
						<input id="type_name" name="type_name" type="text" class="form-control" placeholder="Budget Type" />
							
					</div>
					<div class="input-group" id="div_type_creditordebit" style="display:none">
						<span class="input-group-addon"><i class="fa fa-shopping-basket"></i></span>
						<select id="type_creditordebit" name="type_creditordebit" class="form-control">
							<option value="none">--- Select Transaction Types ---</option>
							<option value="2">Credit</option>
							<option value="1">Debit</option>
						</select>
					</div>
					<br />
				
				<button type="submit" class="save btn btn-primary">Save</button>
				</form>
			</div>
	</div>

{% endblock %}

task_scheduler/templates/task_scheduler/profilepage.html
{% extends 'task_scheduler/layout/top-nav.html' %}
{% load staticfiles %}
{% load humanize %}
{% block content_title %}
Edit Profile
{% endblock %}

{% block content %}

	<div class="box" style="width:70%; margin:auto; padding:25px">
		<form method="POST" class="post-form">{% csrf_token %}
		<div class="box-body">
			<div class="form-group">
				<label>Username:</label>
				<div class="input-group">
					<span class="input-group-addon"><i class="fa fa-user"></i></span>
					<input type="text" class="form-control" value="{{ user.username }}" disabled>
				</div>
            </div>
			
			<div class="form-group">
				<label>Password:</label>
				<div class="input-group">
					<span class="input-group-addon"><i class="fa fa-user"></i></span>
					<input type="password" class="form-control" value="{{ user.password }}" disabled>
				</div>
				<br />
				<a href="#" class="btn btn-warning">Change Password</a>
            </div>

			<div class="form-group">
                  <label>First Name:</label>
				  <div class="input-group">
					  <span class="input-group-addon"><i class="fa fa-user"></i></span>
					  <input type="text" name="id_first_name" class="form-control" value="{{ user.first_name }}">
				  </div>
            </div>
			
			<div class="form-group">
                  <label>Last Name:</label>
				  <div class="input-group">
					  <span class="input-group-addon"><i class="fa fa-user"></i></span>
					  <input type="text" name="id_last_name" class="form-control" value="{{ user.last_name }}">
				  </div>
            </div>
			
			<div class="form-group">
                  <label>Email:</label>
				  <div class="input-group">
					  <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
					  <input type="text" class="form-control" value="{{ user.email }}" disabled>
					  
				  </div>
				<br />
				  <a href="#" class="btn btn-warning">Change Email</a>
            </div>
			
			<div class="form-group">
                  <label>Monthly Budget Target:</label>
				  <div class="input-group">
					  <span class="input-group-addon"><i class="fa fa-money"></i></span>
					  <input type="text" name="id_monthly_budget" class="form-control" value="Rp{{ user.monthly_budget_target|intcomma }} ">
				  </div>
            </div>
			
			<div class="form-group">
                  <label>Total Saving:</label>
				  <div class="input-group">
					  <span class="input-group-addon"><i class="fa fa-money"></i></span>
					  <input type="text" class="form-control" value="Rp{{ user.total_saving|intcomma }}" disabled>
				  </div>
            </div>

			<div class="form-group">
                  <label>This Month's Saving:</label>
				  <div class="input-group">
					  <span class="input-group-addon"><i class="fa fa-money"></i></span>
					  <input type="text" class="form-control" value="Rp{{ user.total_saving|intcomma }}" disabled>
				  </div>
            </div>

			<div class="form-group">
                  <label>Last Month's Saving:</label>
				  <div class="input-group">
					  <span class="input-group-addon"><i class="fa fa-money"></i></span>
					  <input type="text" class="form-control" value="Rp{{ user.total_saving|intcomma }}" disabled>
				  </div>
            </div>
			
			<button type="submit" class="save btn btn-primary">Save Changes</button>
		</div>
    </form>
	</div>

{% endblock %}

task_scheduler/templates/task_scheduler/register.html
{% extends 'task_scheduler/layout/top-nav.html' %}
{% load staticfiles %}

{% load widget_tweaks %}

{% block content_title %}
Register New User
{% endblock %}
{% block content %}
	
    <div class="box" style="width:70%; margin:auto; padding:25px">
		
			<div class="box-body">
				<form method="POST" class="post-form">{% csrf_token %}
					{{ form.non_field_errors }}
					<div class="input-group">
						{{ form.username.errors }}
						<span class="input-group-addon"><i class="fa fa-user"></i></span>
						{% render_field form.username class="form-control" placeholder="Username" %}
					</div>
					<br />
					<div class="input-group">
						{{ form.first_name.errors }}
						<span class="input-group-addon"><i class="fa fa-user"></i></span>
						{% render_field form.first_name class="form-control" placeholder="First Name" %}
					</div>
					<br />
					<div class="input-group">
						{{ form.last_name.errors }}
						<span class="input-group-addon"><i class="fa fa-user"></i></span>
						{% render_field form.last_name class="form-control" placeholder="Last Name" %}
					</div>
					<br />
					<div class="input-group">
						{{ form.last_name.errors }}
						<span class="input-group-addon"><i class="fa fa-envelope"></i></span>
						{% render_field form.email class="form-control" placeholder="Email" %}
					</div>
					<br />
					<div class="input-group">
						{{ form.monthly_budget_target.errors }}
						<span class="input-group-addon"><i class="fa fa-money"></i></span>
						{% render_field form.monthly_budget_target class="form-control" placeholder="Monthly Budget Target" %}
							
					</div>
					<br />
					<div class="input-group">
						{{ form.total_saving.errors }}
						<span class="input-group-addon"><i class="fa fa-money"></i></span>
						{% render_field form.total_saving class="form-control" placeholder="Total Saving" %}
						
					</div>
					<br />
				
				<button type="submit" class="save btn btn-primary">Save</button>
				</form>
			</div>
	</div>

{% endblock %}